# Generated by Django 3.1.2 on 2021-04-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientencounterservice',
            name='patient',
        ),
    ]
