# Generated by Django 3.1.2 on 2021-04-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_delete_appointment'),
        ('medical_services', '0002_remove_patientencounterservice_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounterservice',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
    ]
