# Generated by Django 3.1.2 on 2021-04-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0003_patientencounterservice_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalservice',
            old_name='date',
            new_name='date_created',
        ),
    ]
