# Generated by Django 3.1.2 on 2021-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0004_auto_20210421_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounterservice',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
