# Generated by Django 4.2.4 on 2024-01-30 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('stock_level', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('drug', 'Drug'), ('consummables', 'Consummables')], max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('strength', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('tab', 'Tab'), ('syrup', 'Syrup'), ('injectibles', 'Injectibles')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_take', models.IntegerField()),
                ('times_daily', models.CharField(choices=[('2', 'BD'), ('3', 'TDS'), ('1', 'OD'), ('4', 'QDS'), ('1', 'PRN')], max_length=20)),
                ('no_of_days', models.IntegerField()),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=225, null=True)),
                ('dispensed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('encounter_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.patientencounter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.item')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_dispensed', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.item'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('title', 'slug')},
        ),
    ]
