# Generated by Django 4.0.6 on 2022-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='stock_level',
            field=models.IntegerField(default=0),
        ),
    ]
