# Generated by Django 3.1.2 on 2021-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_prescription_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='strength',
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.CharField(default='500mg', max_length=50),
            preserve_default=False,
        ),
    ]
