# Generated by Django 3.1.2 on 2021-04-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20210416_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV')], default='oral', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='times_daily',
            field=models.CharField(choices=[('bd', 'BD')], max_length=20),
        ),
    ]
