# Generated by Django 3.1.2 on 2021-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20210416_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='times_daily',
            field=models.CharField(choices=[('bd', 'BD'), ('tds', 'TDS'), ('od', 'OD'), ('qds', 'QDS'), ('prn', 'PRN')], max_length=20),
        ),
    ]
