# Generated by Django 3.1.6 on 2021-12-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_dispensary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='times_daily',
            field=models.CharField(choices=[('2', 'BD'), ('3', 'TDS'), ('1', 'OD'), ('4', 'QDS'), ('prn', 'PRN')], max_length=20),
        ),
    ]
