# Generated by Django 3.1.6 on 2021-12-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20211216_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='item',
        ),
        migrations.AddField(
            model_name='prescription',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.brand'),
            preserve_default=False,
        ),
    ]
