# Generated by Django 3.1.6 on 2021-12-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20211230_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='qty',
        ),
        migrations.AddField(
            model_name='dispensary',
            name='qty_dispensed',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
