# Generated by Django 3.1.6 on 2021-12-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_auto_20211230_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
