# Generated by Django 4.0.6 on 2022-08-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_auto_20211231_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='brand',
        ),
        migrations.AddField(
            model_name='prescription',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.item'),
            preserve_default=False,
        ),
    ]
