# Generated by Django 4.0.6 on 2022-09-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_remove_prescription_brand_prescription_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.brand'),
            preserve_default=False,
        ),
    ]
