# Generated by Django 4.0.6 on 2022-09-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_dispensary_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='updated',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispensed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
