# Generated by Django 4.0.6 on 2022-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_remove_prescription_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
