# Generated by Django 4.0.6 on 2022-09-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='radiology_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyrequest'),
        ),
    ]
