# Generated by Django 4.0.6 on 2022-09-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radiology', '0004_auto_20211015_1855'),
        ('labs', '0013_remove_labrequest_patient'),
        ('visits', '0002_patientencounter_pay_status'),
        ('bills', '0001_initial'),
        ('medical_services', '0005_auto_20210730_0917'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.dispensary'),
        ),
        migrations.AddField(
            model_name='bill',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.patientencounter'),
        ),
        migrations.AddField(
            model_name='bill',
            name='lab_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labrequest'),
        ),
        migrations.AddField(
            model_name='bill',
            name='medical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_services.patientencounterservice'),
        ),
        migrations.AddField(
            model_name='bill',
            name='radiology_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyrequest'),
        ),
    ]
