# Generated by Django 3.1.2 on 2021-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20210416_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='action',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('invoice', 'Invoice'), ('receipt', 'Receipt')], default='receipt', max_length=20),
            preserve_default=False,
        ),
    ]
