# Generated by Django 3.1.2 on 2021-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=20),
        ),
    ]
