# Generated by Django 3.1.2 on 2021-08-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
    ]
