# Generated by Django 3.1.2 on 2021-08-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_remove_wallet_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
