# Generated by Django 3.1.2 on 2021-08-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_auto_20210514_1046'),
        ('bills', '0010_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='lab_requst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labrequest'),
        ),
    ]
