# Generated by Django 3.1.2 on 2021-08-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_bill_lab_requst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='lab_requst',
            new_name='lab_request',
        ),
    ]
