# Generated by Django 3.1.2 on 2021-08-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_auto_20210808_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
