# Generated by Django 3.1.2 on 2021-08-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_auto_20210808_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='amount_paid',
        ),
    ]
