# Generated by Django 3.1.2 on 2021-08-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_remove_paymentdetail_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='action',
        ),
    ]
