# Generated by Django 3.1.2 on 2021-08-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_patient_l_g_a'),
        ('bills', '0016_remove_paymentdetail_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
