# Generated by Django 3.1.6 on 2021-10-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_auto_20211015_1855'),
        ('bills', '0017_auto_20210809_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='radiology_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyrequest'),
        ),
    ]
