# Generated by Django 3.1.6 on 2021-10-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_auto_20211015_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='radiology_service',
        ),
    ]
