# Generated by Django 3.1.6 on 2021-10-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_auto_20211015_1855'),
        ('bills', '0019_remove_bill_radiology_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='radiology_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyrequest'),
        ),
    ]
