# Generated by Django 3.1.6 on 2021-12-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_auto_20211230_1632'),
        ('bills', '0020_bill_radiology_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='prescription',
        ),
        migrations.AddField(
            model_name='bill',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.dispensary'),
        ),
    ]
