# Generated by Django 3.1.6 on 2021-12-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_auto_20211230_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
