# Generated by Django 3.1.6 on 2021-12-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0022_auto_20211231_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
