# Generated by Django 3.1.6 on 2022-01-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0023_auto_20211231_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
    ]
