# Generated by Django 3.1.6 on 2022-01-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0025_auto_20220102_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='action',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.billstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.paymenttype'),
        ),
    ]
