# Generated by Django 3.1.6 on 2022-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0026_auto_20220102_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_status',
        ),
    ]
