# Generated by Django 3.1.6 on 2022-01-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0027_remove_bill_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.billstatus'),
        ),
    ]
