# Generated by Django 3.1.6 on 2022-01-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0028_bill_bill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='action',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('invoice', 'Invoice'), ('receipt', 'Receipt')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillStatus',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
