# Generated by Django 3.1.6 on 2022-01-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0030_auto_20220103_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.payment'),
        ),
    ]
