# Generated by Django 4.0.6 on 2022-09-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0031_auto_20220103_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
    ]
