# Generated by Django 3.1.2 on 2021-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210309_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_a_patient',
            field=models.BooleanField(default=False),
        ),
    ]
