# Generated by Django 3.1.2 on 2021-07-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_auto_20210514_1046'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0010_auto_20210706_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labunit')),
            ],
        ),
        migrations.DeleteModel(
            name='SubGroup',
        ),
    ]
