# Generated by Django 3.1.2 on 2021-07-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_auto_20210514_1046'),
        ('accounts', '0011_auto_20210706_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab_unit',
            field=models.ForeignKey(blank=True, help_text='For MedLab staff only', null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labunit'),
        ),
        migrations.DeleteModel(
            name='LabSubGroup',
        ),
    ]
