# Generated by Django 3.1.2 on 2021-03-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitalSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('blood_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('pulse_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('sp_02', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.patientencounter')),
            ],
        ),
        migrations.CreateModel(
            name='PatientNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('nursing_note', 'Nursing Notes'), ('daily_round', 'Daily Rounds'), ('physical_examination', 'Physical Examination'), ('patient_history', 'Patient History'), ('anaesthetic_note', 'Anaesthetic Notes'), ('intervention', 'Intervention')], max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.patientencounter')),
            ],
        ),
    ]
