# Generated by Django 3.1.2 on 2021-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitalsigns',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
