# Generated by Django 3.1.2 on 2021-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_raiseradiologyservice_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseradiologyservice',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
