# Generated by Django 3.1.6 on 2021-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_auto_20210730_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('diagnosis', models.CharField(blank=True, max_length=225, null=True)),
                ('other_findings', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('unit', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='raiseradiologyservice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='raiseradiologyservice',
            name='encounter_no',
        ),
        migrations.RemoveField(
            model_name='raiseradiologyservice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='raiseradiologyservice',
            name='radiology_service',
        ),
    ]
