# Generated by Django 4.0.6 on 2022-09-29 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0002_patientencounter_pay_status'),
        ('patients', '0035_auto_20211226_1411'),
        ('radiology', '0004_auto_20211015_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaiseRadiologyService',
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='radiologyrequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='clinical_info',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='encounter_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visits.patientencounter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='radiology_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyservice'),
            preserve_default=False,
        ),
    ]
