# Generated by Django 3.1.6 on 2021-10-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_auto_20211015_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='clinical_info',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
