# Generated by Django 3.1.6 on 2021-10-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='female_only',
            field=models.BooleanField(default=False),
        ),
    ]
