# Generated by Django 3.1.6 on 2021-11-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_ward_female_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ('clinic',)},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ('ward',)},
        ),
    ]
