# Generated by Django 3.1.6 on 2021-11-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20211119_1059'),
        ('locations', '0004_auto_20211111_1605'),
    ]

    operations = [
    ]
