# Generated by Django 3.1.2 on 2021-03-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=10)),
                ('phone_1', models.CharField(max_length=11)),
                ('phone_2', models.CharField(blank=True, max_length=11, null=True)),
                ('country', models.CharField(choices=[('nigeria', 'Nigeria')], default='Nigeria', max_length=100)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('nasarawa', 'Nasarawa')], max_length=100)),
                ('l_g_a', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('next_of_kin_relationship', models.CharField(choices=[('spouse', 'Spouse'), ('brother', 'Brother'), ('sister', 'Sister'), ('father', 'Father'), ('mother', 'Mother'), ('cousin', 'Cousin'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('neighbour', 'Neighbour'), ('son', 'Son'), ('daughter', 'Daughter'), ('son', 'Son')], max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('next_of_kin_address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('new', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
