# Generated by Django 3.1.2 on 2021-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
