# Generated by Django 4.2.4 on 2024-01-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='l_g_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.lga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.state'),
            preserve_default=False,
        ),
    ]
