# Generated by Django 4.2.4 on 2024-01-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_continent_country_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='lga',
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lga',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
