# Generated by Django 3.1.2 on 2021-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210311_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
