# Generated by Django 4.2.4 on 2024-02-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_lga_lga_lga_state_alter_lga_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
