# Generated by Django 3.1.2 on 2021-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('seen', 'seen'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
