# Generated by Django 3.1.2 on 2021-04-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_appointment_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
