# Generated by Django 3.1.2 on 2021-04-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20210429_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientImage',
        ),
    ]
