# Generated by Django 3.1.2 on 2021-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20210429_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, default='image/male.jpg', null=True, upload_to='image/'),
        ),
    ]
