# Generated by Django 3.1.2 on 2021-07-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20210724_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LGA',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
