# Generated by Django 3.1.2 on 2021-07-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_lga_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LGA',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
