# Generated by Django 3.1.2 on 2021-07-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_lga_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='l_g_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.lga'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.state'),
        ),
    ]
