# Generated by Django 3.1.2 on 2021-07-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20210724_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='l_g_a',
        ),
    ]
