# Generated by Django 3.1.2 on 2021-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20210724_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='l_g_a',
            field=models.CharField(default='keffi', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(choices=[('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa-ibom', 'Akwa-Ibom'), ('delta', 'Delta'), ('edo', 'Edo'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('ondo', 'Ondo'), ('imo', 'Imo'), ('bauchi', 'Bauchi'), ('plateau', 'Plateau'), ('ogun', 'Ogun'), ('kaduna', 'Kaduna'), ('katsina', 'Katsina'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('benue', 'Benue'), ('kogi', 'Kogi'), ('fct(Abuja)', 'FCT(Abuja)'), ('ebonyi', 'Ebonyi'), ('cross-rivers', 'Cross-Rivers')], default='nasarawa', max_length=100),
        ),
    ]
