# Generated by Django 3.1.2 on 2021-07-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_auto_20210727_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='l_g_a',
        ),
    ]
