# Generated by Django 3.1.2 on 2021-07-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_patient_l_g_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='l_g_a',
        ),
    ]
