# Generated by Django 3.1.2 on 2021-07-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_patient_lga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='lga',
            new_name='l_g_a',
        ),
        migrations.DeleteModel(
            name='LGA',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
