# Generated by Django 3.1.2 on 2021-07-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_auto_20210730_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='l_g_a',
        ),
    ]
