# Generated by Django 3.1.6 on 2021-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_auto_20210916_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
