# Generated by Django 4.2.4 on 2024-02-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makediagnosis',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='makediagnosis',
            name='icd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis'),
        ),
        migrations.AddField(
            model_name='makediagnosis',
            name='user_defined',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='clinic',
            field=models.ManyToManyField(blank=True, null=True, to='locations.clinic'),
        ),
    ]
