# Generated by Django 3.1.6 on 2021-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_auto_20210923_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makediagosis',
            name='type',
        ),
        migrations.AddField(
            model_name='makediagosis',
            name='preliminary',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='DiagnosisType',
        ),
    ]
