# Generated by Django 3.1.6 on 2021-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20210924_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makediagosis',
            name='preliminary',
        ),
        migrations.AddField(
            model_name='makediagosis',
            name='final',
            field=models.BooleanField(default=True),
        ),
    ]
