# Generated by Django 3.1.2 on 2021-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
    ]
