# Generated by Django 3.1.2 on 2021-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_labrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='test',
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test',
            field=models.ManyToManyField(to='labs.LabTest'),
        ),
    ]
