# Generated by Django 3.1.2 on 2021-05-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20210503_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabRequest',
        ),
    ]
