# Generated by Django 3.1.2 on 2021-05-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_labrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.labtest'),
        ),
    ]
