# Generated by Django 3.1.2 on 2021-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_auto_20210506_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
