# Generated by Django 3.1.2 on 2021-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_labtest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
