# Generated by Django 3.1.2 on 2021-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_labresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
