# Generated by Django 3.1.2 on 2021-05-14 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0011_labrequest_accepted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabResults',
            new_name='LabResult',
        ),
    ]
