# Generated by Django 4.0.6 on 2022-09-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_auto_20210514_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='patient',
        ),
    ]
